version: 0.2
env:
  variables:
    S3_BUCKET: "2175051-sf-cicd-test-bucket"
    AWS_REGION: "ap-northeast-1"
    REPOSITORY_URI: "477460359712.dkr.ecr.ap-northeast-1.amazonaws.com/2175051_ecs-test"
phases:
  install:
    commands:
      - echo No Install phase
  pre_build:
    on-failure: ABORT
    commands:
      - aws cloudformation validate-template --template-body file://template.yml
  build:
    on-failure: ABORT
    commands:
      - echo "Packaging Lambda source code..."
      - aws cloudformation package --template template.yml --s3-bucket ${S3_BUCKET} --output-template packaged-template.yml
  post_build:
    on-failure: ABORT
    commands:
      - echo Build completed on `date`
      
artifacts:
  files:
    - packaged-template.yml