version: 0.2

env:
  variables:
    SRC_REGION: "ap-northeast-1"
    DST_REGION: "ap-northeast-3"
    SRC_REPO: "2175051-test-repo"
    DST_REPO: "2175051-test-dr-repo"
    BRANCH: "main"
phases:
  install:
    on-failure: ABORT
    commands:
      - echo Install started on `date`
      - pip install git-remote-codecommit
  pre_build:
    commands:
      - echo No Pre Build phase
  build:
    on-failure: ABORT
    commands:
      - echo Build started on `date`
      - git clone codecommit::${SRC_REGION}://${SRC_REPO}
      - cd ${SRC_REPO}
      - git remote set-url origin codecommit::${DST_REGION}://${DST_REPO}
      - git push origin ${BRANCH}
  post_build:
    on-failure: ABORT
    commands:
      - echo Build completed on `date`
