version: 0.2

phases:
  install:
    commands:
      - echo No Pre Install phase
  pre_build:
    commands:
      - echo No Pre Build phase
  build:
    commands:
#      - "SFCurrentVersion=$(echo $(aws stepfunctions describe-state-machine-alias --state-machine-alias-arn arn:aws:states:ap-northeast-1:477460359712:stateMachine:2175051-test-MyStateMachine:prod | grep stateMachineVersionArn | tail -1 | cut -d : -f 9 | tr -cd 0-9))"
      - "aws stepfunctions update-state-machine --state-machine-arn arn:aws:states:ap-northeast-1:477460359712:stateMachine:2175051-test-MyStateMachine --definition file://lower1_definition.json"
      - "aws stepfunctions update-state-machine --state-machine-arn arn:aws:states:ap-northeast-1:477460359712:stateMachine:2175051-Lower-MyStateMachine --definition file://lower2_definition.json"
      - "aws stepfunctions update-state-machine --state-machine-arn arn:aws:states:ap-northeast-1:477460359712:stateMachine:2175051-Upper-MyStateMachine --definition file://upper_definition.json"
      - sleep 10
  post_build:
    commands:
      - echo Build completed on `date`
      - ls
#      - "aws stepfunctions publish-state-machine-version --state-machine-arn arn:aws:states:ap-northeast-1:477460359712:stateMachine:2175051-test-MyStateMachine --description 'update version'"
#      - "SFTargetVersion=$(echo $(aws stepfunctions list-state-machine-versions --state-machine-arn arn:aws:states:ap-northeast-1:477460359712:stateMachine:2175051-test-MyStateMachine | grep stateMachineVersionArn | head -1 | cut -d : -f 9 | tr -cd 0-9))"
#      - echo $SFCurrentVersion
#      - echo $SFTargetVersion
#      - "aws stepfunctions update-state-machine-alias --state-machine-alias-arn arn:aws:states:ap-northeast-1:477460359712:stateMachine:2175051-test-MyStateMachine:prod --routing-configuration stateMachineVersionArn=arn:aws:states:ap-northeast-1:477460359712:stateMachine:2175051-test-MyStateMachine:$SFTargetVersion,weight=100"
#      - "aws stepfunctions delete-state-machine-version --state-machine-version-arn arn:aws:states:ap-northeast-1:477460359712:stateMachine:2175051-test-MyStateMachine:$SFCurrentVersion"