version: 0.2

phases:
  install:
    commands:
      - echo Install started on `date`
      - pip install git-remote-codecommit
  pre_build:
    commands:
      - echo No Pre Build phase
  build:
    on-failure: ABORT
    commands:
      - echo Build started on `date`
      - git config --global pull.rebase false
      - git clone codecommit::ap-northeast-3://2175051-test-dr-repo
      - cd 2175051-test-dr-repo
      - git remote add torikomi_repo codecommit::ap-northeast-1://2175051-test-repo
      - git pull torikomi_repo main
      - git add .
      - git commit -m 'get source repo'
      - git remote rm torikomi_repo
      - git push origin main
  post_build:
    on-failure: ABORT
    commands:
      - echo Build completed on `date`
