version: 0.2
env:
  variables:
    S3_BUCKET: "2175051-sf-cicd-test-bucket/glue"
    
phases:
  install:
    commands:
      - echo No Install phase
  pre_build:
    on-failure: ABORT
    commands:
      - aws cloudformation validate-template --template-body file://template.yml
  build:
    on-failure: ABORT
    commands:
      - echo "Uploading Glue Script..."
      - sh glue_script_upload.sh
      - echo "Deploying Glue Script..."
      - aws cloudformation deploy --template template.yml --stack-name glue-cfn-test-deploy
  post_build:
    on-failure: ABORT
    commands:
      - echo Build completed on `date`