version: 0.2

phases:
  install:
    commands:
      - echo Install started on `date`
      - pip install git-remote-codecommit
  pre_build:
    commands:
      - echo No Pre Build phase
  build:
    on-failure: ABORT
    commands:
      - echo Build started on `date`
      - git clone codecommit::ap-northeast-1://2175051-test-repo
      - pwd
      - ls -l
#      - sh git_connect.sh
  post_build:
    on-failure: ABORT
    commands:
      - echo Build completed on `date`
