version: 0.2

phases:
  install:
    commands:
      - echo No Install phase
  pre_build:
    commands:
      - echo No Pre Build phase
  build:
    on-failure: ABORT
    commands:
      - echo Build started on `date`
      - git_connect.sh
  post_build:
    on-failure: ABORT
    commands:
      - echo Build completed on `date`
