version: 0.2
env:
  variables:
    S3_BUCKET: "2175051-sf-cicd-test-bucket"
    AWS_REGION: "ap-northeast-1"

phases:
  install:
    commands:
      - echo  Install phase
      - unzip aws-sam-cli-linux-x86_64.zip -d sam-installation
      - sudo ./sam-installation/install --update
      - sam --version
  pre_build:
    on-failure: ABORT
    commands:
      - echo "Start checking sam template file..."
      - sam validate --lint --template template.yml
  build:
    on-failure: ABORT
    commands:
      - echo "Start deploying Statemachine And Lambda Function..."
#      - sam build
      - sam deploy --no-confirm-changeset --no-fail-on-empty-changeset
  post_build:
    on-failure: ABORT
    commands:
      - echo Build completed on `date`
