version: 0.2

phases:
  install:
    commands:
      - echo No Install phase
  pre_build:
    commands:
      - echo No Pre Build phase
  build:
    on-failure: ABORT
    commands:
      - echo Build started on `date`
      - sh lambda_deploy.sh

      - sleep 10
  post_build:
    on-failure: ABORT
    commands:
      - echo Build completed on `date`
      - ls
      - sh lambda_alias.sh