version = 0.1
[default.deploy.parameters]
stack_name = "sam-deploy-test"
s3_bucket = "2175051-sf-cicd-test-bucket"
s3_prefix = "sam"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND"
image_repositories = []
