version = 0.1
[default.deploy.parameters]
stack_name = "sam-deploy-test"
resolve_s3 = true
s3_prefix = "sam-deploy-test"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_NAMED_IAM"
disable_rollback = true
parameter_overrides = "StateMachine1Name=\"2175051-CFn-testStatemachine-lower1\" StateMachine2Name=\"2175051-CFn-testStatemachine-lower2\" StateMachine3Name=\"2175051-CFn-testStatemachine-upper\" LambdaFunction1Name=\"2175051-CFn-testLambda-1\" LambdaFunction2Name=\"2175051-CFn-testLambda-2\" LambdaFunction3Name=\"2175051-CFn-testLambda-3\""
image_repositories = []
