AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31


Parameters:
  NestResourceName:
    Description: 'テスト用'
    Type: String
  VPCID:
    Description: 'VPCID'
    Type: String
  SgIngCidrIp1:
    Description: 'SgIngCidrIp1'
    Type: String
  SgIngFromPort1:
    Description: 'SgIngFromPort1'
    Type: String
  SgIngCidrIp2:
    Description: 'SgIngCidrIp2'
    Type: String
  SgIngFromPort2:
    Description: 'SgIngFromPort2'
    Type: String

Resources:
  ###################################################
  # SecurityGroup
  ###################################################
  TestSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub ${NestResourceName}-sg
      GroupDescription: Allow http to client host
      VpcId: !Sub ${VPCID}
      Tags: 
        - Key: Name
          Value: !Sub ${NestResourceName}-sg
  TestSGOutboundRule1:
    Type: AWS::EC2::SecurityGroupEgress
    Properties:
      IpProtocol: -1
      CidrIp: 0.0.0.0/0
      GroupId: !GetAtt TestSG.GroupId
  TestSGInboundRule1:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      IpProtocol: tcp
      CidrIp: !Sub ${SgIngCidrIp1}
      FromPort: !Sub ${SgIngFromPort1}
      ToPort: !Sub ${SgIngFromPort1}
      GroupId: !GetAtt TestSG.GroupId
  TestSGInboundRule2:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      IpProtocol: tcp
      CidrIp: !Sub ${SgIngCidrIp2}
      FromPort: !Sub ${SgIngFromPort2}
      ToPort: !Sub ${SgIngFromPort2}
      GroupId: !GetAtt TestSG.GroupId


      # アウトバウンド設定
#      SecurityGroupEgress:
#        - CidrIp: 0.0.0.0/0
#          IpProtocol: -1
#      # インバウンド設定
#      SecurityGroupIngress:
#        - CidrIp: !Sub ${SgIngCidrIp1}
#          FromPort: !Sub ${SgIngFromPort1}
#          IpProtocol: tcp
#          ToPort: !Sub ${SgIngFromPort1}
#        - CidrIp: !Sub ${SgIngCidrIp2}
#          FromPort: !Sub ${SgIngFromPort2}
#          IpProtocol: tcp
#          ToPort: !Sub ${SgIngFromPort2}

Outputs:
  SGID:
    Value: !GetAtt TestSG.GroupId
    Export:
      Name: test-sg-id

