AWSTemplateFormatVersion: '2010-09-09'
Description: AWS Glue Job Stack
Mappings:
  TagsMap:
    EnvName:
      Environment: "Indev"
      Service: "bcpf"
Parameters:
  AwsAccount:
    Description: 'AWSアカウント番号'
    Type: String
    Default: '477460359712'

  GlueCommonRole:
    Description: 'GlueJob共通IAMロール'
    Type: String
    Default: '2175051-testGlueRole'

  GlueJobName1:
    Description: 'GlueJob名1'
    Type: String
    Default: '2175051-CFnTest-GlueJob1'
  GlueJobName2:
    Description: 'GlueJob名2'
    Type: String
    Default: '2175051-CFnTest-GlueJob2'
  GlueJobName3:
    Description: 'GlueJob名3'
    Type: String
    Default: '2175051-CFnTest-GlueJob3'
Resources:
  GlueJob1:
    Type: AWS::Glue::Job
    Properties:
      Name: !Sub ${GlueJobName1}
      Role: arn:aws:iam::${AwsAccount}:role/${GlueCommonRole}
      Command:
        Name: pythonshell
        ScriptLocation: s3://2175051-sf-cicd-test-bucket/glue/2175051-CFnTestJob1/glue_script.py
      MaxRetries: 0
      Timeout: 5
      ExecutionProperty:
        MaxConcurrentRuns: 5
      DefaultArguments:
        '--TempDir': 's3://2175051-sf-cicd-test-bucket/glue/tmp/'
        '--extra-py-files': 's3://2175051-sf-cicd-test-bucket/glue/lib/glue_script.py'
      Tags: 
        Key: Name
        Value: !Sub ${GlueJobName1}

  GlueJob2:
    Type: AWS::Glue::Job
    Properties:
      Name: !Sub ${GlueJobName2}
      Role: arn:aws:iam::${AwsAccount}:role/${GlueCommonRole}
      Command:
        Name: pythonshell
        ScriptLocation: s3://2175051-sf-cicd-test-bucket/glue/2175051-CFnTestJob2/glue_script.py
      MaxRetries: 0
      Timeout: 5
      ExecutionProperty:
        MaxConcurrentRuns: 5
      DefaultArguments:
        '--TempDir': 's3://2175051-sf-cicd-test-bucket/glue/tmp/'
        '--extra-py-files': 's3://2175051-sf-cicd-test-bucket/glue/lib/glue_script.py'

  GlueJob3:
    Type: AWS::Glue::Job
    Properties:
      Name: !Sub ${GlueJobName3}
      Role: arn:aws:iam::${AwsAccount}:role/${GlueCommonRole}
      Command:
        Name: pythonshell
        ScriptLocation: s3://2175051-sf-cicd-test-bucket/glue/2175051-CFnTestJob3/glue_script.py
      MaxRetries: 0
      Timeout: 5
      ExecutionProperty:
        MaxConcurrentRuns: 5
      DefaultArguments:
        '--TempDir': 's3://2175051-sf-cicd-test-bucket/glue/tmp/'
        '--extra-py-files': 's3://2175051-sf-cicd-test-bucket/glue/lib/glue_script.py'
