AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31


Parameters:
  NestAwsAccount:
    Description: 'AWSアカウント番号'
    Type: String
    Default: '477460359712'
  NestSubscriptionFilterRole:
    Description: 'サブスクリプションフィルタ用IAMロール'
    Type: String
    Default: '2175051-cwltofirehose-role'
  NestKDFCommonRole:
    Description: 'KDF用IAMロール'
    Type: String
    Default: '2175051-firehosetos3-role'
  NestResourceName:
    Description: 'テスト用Lambda'
    Type: String
    Default: '2175051-cfntest-resource'
  LogGroupName:
    Description: 'テスト用Lambda'
    Type: String
    Default: 'aws/lambda/2175051-cfntest-lggr'
  NestTargetS3Bacuket:
    Description: 'KDFターゲットS3バケット'
    Type: String
    Default: 'arn:aws:s3:::2175051-sf-cicd-test-bucket'
Resources:
  ###################################################
  # Log Transfer
  ###################################################
  #Lambda用ロググループ
  TestLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub ${LogGroupName}
      RetentionInDays: 7
      Tags: 
        - Key: Name
          Value: !Sub ${LogGroupName}

  TestSubscriptionFilter:
    Type: AWS::Logs::SubscriptionFilter
    Properties:
      DestinationArn: !GetAtt TestKDF.Arn
      Distribution: Random
      FilterName: !Sub ${NestResourceName}-subscription-s3-filter
      FilterPattern: ''
      LogGroupName: !Ref TestLogGroup
      RoleArn: !Sub arn:aws:iam::${NestAwsAccount}:role/${NestSubscriptionFilterRole}
      
  TestKDF:
    Type: AWS::KinesisFirehose::DeliveryStream
    Properties:
      DeliveryStreamName: !Sub ${NestResourceName}-delivery-stream
      DeliveryStreamType: DirectPut
      ExtendedS3DestinationConfiguration: 
        BucketARN: !Sub ${NestTargetS3Bacuket}
        BufferingHints:
          IntervalInSeconds: '60'
          SizeInMBs: '50'
        RoleARN: !Sub arn:aws:iam::${NestAwsAccount}:role/${NestKDFCommonRole}
        CloudWatchLoggingOptions:
          Enabled: true
          LogGroupName: !Sub '/aws/kinesisfirehose/${NestResourceName}-delivery-stream'
          LogStreamName: S3Delivery
        CompressionFormat:  GZIP
        EncryptionConfiguration:
          NoEncryptionConfig: NoEncryption
        ErrorOutputPrefix: !Sub 'logs/error/${NestResourceName}'
        Prefix: !Sub 'logs/info/${NestResourceName}'
      Tags: 
        - Key: Name
          Value: !Sub ${NestResourceName}-delivery-stream
