AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: "Batch Resource Template"
Mappings:
  TagsMap:
    EnvName:
      Environment: "Indev"
      Service: "bcpf"
Parameters:
  AwsAccount:
    Description: 'AWSアカウント番号'
    Type: String
    Default: '477460359712'

  ECSCommonRole:
    Description: 'ECS共通IAMロール'
    Type: String
    Default: 'ecsTaskExecutionRole'

  EcsTaskName1:
    Description: '定点バッチ用ECSタスク'
    Type: String
    Default: '2175051-batch-task'
  EcsContainerName1:
    Description: '定点バッチ用ECSコンテナ'
    Type: String
    Default: '2175051-batch-container'
  EcrName1:
    Description: '定点バッチ用ECR'
    Type: String
    Default: '2175051_ecs-test'

Resources:
  #ECSTask      
  ECSTask1:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Cpu: 256
      ExecutionRoleArn: !Sub arn:aws:iam::${AwsAccount}:role/${ECSCommonRole}
      Family: !Sub ${EcsTaskName1}
      Memory: 512
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      TaskRoleArn: !Sub arn:aws:iam::${AwsAccount}:role/${ECSCommonRole}
      ContainerDefinitions:
        - Image: !Sub ${AwsAccount}.dkr.ecr.ap-northeast-1.amazonaws.com/${EcrName1}:latest
          Essential: true
          Name: !Sub ${EcsContainerName1}
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-region: ap-northeast-1
              awslogs-group: !Sub ${EcsContainerName1}-lg
              awslogs-stream-prefix: ecs
          Environment:  ################設定例
            - Name: SSMParam
              ValueFrom: arn:aws:ssm:ap-northeast-1:477460359712:parameter/2175051_paramTest
      Tags: 
        - Key: Name
          Value: !Sub ${EcsTaskName1}
        - Key: Environment
          Value: !FindInMap [ TagsMap, EnvName, Environment ]
        - Key: Service
          Value: !FindInMap [ TagsMap, EnvName, Service ]