AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31


Parameters:
  AwsAccount:
    Description: 'AWSアカウント番号'
    Type: String
    Default: '477460359712'

  SubscriptionFilterRole:
    Description: 'サブスクリプションフィルタ用IAMロール'
    Type: String
    Default: '2175051-cwltofirehose-role'
  KDFCommonRole:
    Description: 'KDF用IAMロール'
    Type: String
    Default: '2175051-firehosetos3-role'
    
  ResourceName:
    Description: 'テスト用'
    Type: String
    Default: '2175051-cfntest-lggr'
    
  TargetS3Bacuket:
    Description: 'KDFターゲットS3バケット'
    Type: String
    Default: 'arn:aws:s3:::2175051-sf-cicd-test-bucket'

Resources:
  LogTransferStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./log_transfer_template.yaml
      Parameters:
        NestAwsAccount: !Sub ${AwsAccount}
        NestSubscriptionFilterRole: !Sub ${SubscriptionFilterRole}
        NestKDFCommonRole: !Sub ${KDFCommonRole}
        NestResourceName: !Sub ${ResourceName}
        LogGroupName: !Sub aws/lambda/${ResourceName}
        NestTargetS3Bacuket: !Sub ${TargetS3Bacuket}
        
#  LambdaStack:
#    Type: AWS::CloudFormation::Stack
#    Properties:
#      TemplateURL: ./lambda_template.yaml
#      Parameters:
#        NestVPCRange: !Ref VPCRange
#        NestSubnetRange1: !Ref SubnetRange1

