AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31


Parameters:
  AwsAccount:
    Description: 'AWSアカウント番号'
    Type: String
    Default: '477460359712'
  PrivateSubnet1:
    Description: 'プライベートサブネット1'
    Type: String
    Default: 'subnet-08b3b53b973fe0d23'
  PrivateSubnet2:
    Description: 'プライベートサブネット2'
    Type: String
    Default: 'subnet-08505629ae83788fc'
  LambdaCommonRole:
    Description: 'Lambda共通IAMロール'
    Type: String
    Default: '2175051_lambda-common-role'
  SubscriptionFilterRole:
    Description: 'サブスクリプションフィルタ用IAMロール'
    Type: String
    Default: '2175051-cwltofirehose-role'
  KDFCommonRole:
    Description: 'KDF用IAMロール'
    Type: String
    Default: '2175051-firehosetos3-role'
    
  LambdaFunctionName1:
    Description: 'テスト用Lambda'
    Type: String
    Default: '2175051-cfntest-lambda01'
  LambdaLayerName2:
    Description: 'openpyxl用レイヤー'
    Type: String
    Default: 'openpyxl'
    
  TargetS3Bacuket:
    Description: 'KDFターゲットS3バケット'
    Type: String
    Default: 'arn:aws:s3:::2175051-sf-cicd-test-bucket'
    
  VPCID:
    Description: 'VPCID'
    Type: String
    Default: 'vpc-0d8f5785aec76fd74'
  SgIngCidrIp1:
    Description: 'SgIngCidrIp1'
    Type: String
    Default: '192.168.0.1/32'
  SgIngFromPort1:
    Description: 'SgIngFromPort1'
    Type: String
    Default: '22'
  SgIngCidrIp2:
    Description: 'SgIngCidrIp2'
    Type: String
    Default: '192.168.0.2/32'
  SgIngFromPort2:
    Description: 'SgIngFromPort2'
    Type: String
    Default: '443'

Resources:
  LogTransferStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./log_transfer_template.yml
      Parameters:
        NestResourceName: !Sub ${LambdaFunctionName1}
        NestAwsAccount: !Sub ${AwsAccount}
        NestSubscriptionFilterRole: !Sub ${SubscriptionFilterRole}
        NestKDFCommonRole: !Sub ${KDFCommonRole}
        LogGroupName: !Join [ "", [/aws/lambda/, !Ref LambdaFunctionName1 ]]
        NestTargetS3Bacuket: !Sub ${TargetS3Bacuket}
        
  SGStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./sg_template.yml
      Parameters:
        NestResourceName: !Sub ${LambdaFunctionName1}
        VPCID: !Sub ${VPCID}
        SgIngCidrIp1: !Sub ${SgIngCidrIp1}
        SgIngFromPort1: !Sub ${SgIngFromPort1}
        SgIngCidrIp2: !Sub ${SgIngCidrIp2}
        SgIngFromPort2: !Sub ${SgIngFromPort2}
        
  LambdaStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./lambda_template.yml
      Parameters:
        LambdaFunctionName1: !Sub ${LambdaFunctionName1}
        LambdaLayerName2: !Sub ${LambdaLayerName2}
        AwsAccount: !Sub ${AwsAccount}
        PrivateSubnet1: !Sub ${PrivateSubnet1}
        PrivateSubnet2: !Sub ${PrivateSubnet2}
        LambdaCommonRole: !Sub ${LambdaCommonRole}