AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Mappings:
  TagsMap:
    EnvName:
      Environment: "Indev"
      Service: "bcpf"
Parameters:
  PrivateSubnet1:
    Description: 'プライベートサブネット1'
    Type: String
    Default: 'subnet-08b3b53b973fe0d23'
  PrivateSubnet2:
    Description: 'プライベートサブネット2'
    Type: String
    Default: 'subnet-08b3b53b973fe0d23'
  LambdaSG:
    Description: '仮LambdaSG'
    Type: String
    Default: 'sg-0bcb3b17a0d7db869'
    
  StateMachineName1:
    Description: 'ダウンロードファイル作成用ステートマシン'
    Type: String
    Default: 'bo01-indev-bcpf-make-download-file-statemachine'
    
  LambdaFunctionName1:
    Description: 'ファイル形式チェック用Lambda'
    Type: String
    Default: 'bo01-indev-bcpf-check-file-lambda'
  LambdaFunctionNameDir1:
    Description: 'ファイル形式チェック用Lambda'
    Type: String
    Default: 'functions/bo01-indev-bcpf-check-file-lambda'

  LambdaLayerName1:
    Description: 'psycopg2用レイヤー'
    Type: String
    Default: 'psycopg2'
  LambdaLayerName2:
    Description: 'openpyxl用レイヤー'
    Type: String
    Default: 'openpyxl'
    
Resources:
#Lambda Layer作成
  LambdaLayer1:
    Type: "AWS::Serverless::LayerVersion"
    Properties:
      LayerName: !Sub ${LambdaLayerName1}
      Description: !Sub ${LambdaLayerName1}
      CompatibleArchitectures: 
        - x86_64
      CompatibleRuntimes: 
        - python3.11
      ContentUri: layer/psycopg2/
  LambdaLayer2:
    Type: "AWS::Serverless::LayerVersion"
    Properties:
      LayerName: !Sub ${LambdaLayerName2}
      Description: !Sub ${LambdaLayerName2}
      CompatibleArchitectures: 
        - x86_64
      CompatibleRuntimes: 
        - python3.11
      ContentUri: layer/openpyxl/
      
#LambdaSAM
  LambdaFunction1:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${LambdaFunctionName1}
      CodeUri: functions/bo01-indev-bcpf-check-file-lambda
      Handler: lambda_function.lambda_handler
      Role: !GetAtt LambdaExecutionRole1.Arn
      Runtime: python3.11
      Architectures: 
        - x86_64
      MemorySize: 128
      EphemeralStorage:
        Size: 512
      Timeout: 30
      VpcConfig: 
        SecurityGroupIds:
          - !Sub ${LambdaSG} ###### 暫定でdefault
        SubnetIds:
          - !Sub ${PrivateSubnet1}
          - !Sub ${PrivateSubnet2}
      Tags: 
        Name: !Sub ${LambdaFunctionName1}
      Layers: 
        - !Ref LambdaLayer1
        - !Ref LambdaLayer2
      Environment: 
        Variables:
          KeyName1: Value1
          KeyName2: Value2

                
#StepFunctionsSAM
  StateMachine1:
    Type: AWS::Serverless::StateMachine
    Properties:
      Name: !Sub ${StateMachineName1}
      DefinitionUri: statemachine/bo01-indev-bcpf-make-download-file-statemachine.json
      Role: !GetAtt StateMachineExecutionRole1.Arn
      Type: STANDARD
      Logging:
        Level: ALL
        IncludeExecutionData: True
        Destinations:
          - CloudWatchLogsLogGroup:
              LogGroupArn: !GetAtt StateMachine1LogGroup.Arn
      Tags: 
        Name: !Sub ${StateMachineName1}
        Environment: !FindInMap [ TagsMap, EnvName, Environment ]
        Service: !FindInMap [ TagsMap, EnvName, Service ]
            
#ステートマシン用ロググループ
  StateMachine1LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Join [ "", [ '/aws/states/', !Sub '${StateMachineName1}', '-lg' ] ]
      RetentionInDays: 7
      Tags: 
        - Key: Name
          Value: !Join [ "", [ '/aws/states/', !Sub '${StateMachineName1}', '-lg' ] ]






#IAM
  LambdaExecutionRole1:
    Type: AWS::IAM::Role
    Properties:
      RoleName : !Sub ${LambdaFunctionName1}-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: !Sub ${LambdaFunctionName1}-policy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - logs:TagResource
                  - ec2:*
                Resource: '*'
      Tags: 
        - Key: Name
          Value: !Sub ${LambdaFunctionName1}-role

  StateMachineExecutionRole1:
    Type: AWS::IAM::Role
    Properties:
      RoleName : !Sub ${StateMachineName1}-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: states.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: !Sub ${StateMachineName1}-policy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - logs:*
                  - lambda:InvokeFunction
                  - states:*
                Resource: '*'
      Tags: 
        - Key: Name
          Value: !Sub ${StateMachineName1}-role

