AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::LanguageExtensions'
Transform: AWS::Serverless-2016-10-31


Parameters:
#  AwsAccount:
#    Description: 'AWSアカウント番号'
#    Type: String
#    Default: '477460359712'
#  SubscriptionFilterRole:
#    Description: 'サブスクリプションフィルタ用IAMロール'
#    Type: String
#    Default: '2175051-cwltofirehose-role'
#  KDFCommonRole:
#    Description: 'KDF用IAMロール'
#    Type: String
#    Default: '2175051-firehosetos3-role'
#  TargetS3Bacuket:
#    Description: 'KDFターゲットS3バケット'
#    Type: String
#    Default: 'arn:aws:s3:::2175051-sf-cicd-test-bucket'
  LogGroupName:
    Description: 'リソース名'
    Type: String
    Default: 'cfntest-2175051-lggr'

#  ResourceList:
#    Type: List<String>
#    Default: '2175051-CFnLoopTest-A,2175051-CFnLoopTest-B,2175051-CFnLoopTest-C'
    
    
#Mappings: 
#  LggrMappings: 
#    TestA: 
#      ResourceName: "2175051-CFnLoopTest-A"
#      LogGroupName: "2175051-CFnLoopTest-A-lggr"
#    TestB: 
#      ResourceName: "2175051-CFnLoopTest-B"
#      LogGroupName: "2175051-CFnLoopTest-B-lggr"
#    TestC: 
#      ResourceName: "2175051-CFnLoopTest-C"
#      LogGroupName: "2175051-CFnLoopTest-C-lggr"
      
Resources:
  ###################################################
  # Log Transfer
  ###################################################
  #Lambda用ロググループ
  'Fn::ForEach::Lggrloops':
  - Lggritems
  - - Testloggrname
  - '${Lggritems}':
#  TestLoggr:
      Type: AWS::Logs::LogGroup
      Properties:
        LogGroupName: !Sub ${Lggritems}
#        LogGroupName: !FindInMap
#          - LggrMappings
#        - !Ref lggrItems
#          - TestA
#          - LogGroupName
      RetentionInDays: 7
#        Tags: 
#          - Key: Name
#            Value: !FindInMap
#              - LggrMappings
#              - !Ref lggrItems
#              - ResourceName

#  TestSubscriptionFilter:
#    Type: AWS::Logs::SubscriptionFilter
#    Properties:
#      DestinationArn: !GetAtt TestKDF.Arn
#      Distribution: Random
#      FilterName: !Sub ${ResourceName}-subscription-s3-filter
#      FilterPattern: ''
#      LogGroupName: !Ref TestLogGroup
#      RoleArn: !Sub arn:aws:iam::${AwsAccount}:role/${SubscriptionFilterRole}
      
#  TestKDF:
#    Type: AWS::KinesisFirehose::DeliveryStream
#    Properties:
#      DeliveryStreamName: !Sub ${ResourceName}-delivery-stream
#      DeliveryStreamType: DirectPut
#      ExtendedS3DestinationConfiguration: 
#        BucketARN: !Sub ${TargetS3Bacuket}
#        BufferingHints:
#          IntervalInSeconds: '60'
#          SizeInMBs: '50'
#        RoleARN: !Sub arn:aws:iam::${AwsAccount}:role/${KDFCommonRole}
#        CloudWatchLoggingOptions:
#          Enabled: true
#          LogGroupName: !Sub '/aws/kinesisfirehose/${ResourceName}-delivery-stream'
#          LogStreamName: S3Delivery
#        CompressionFormat:  GZIP
#        EncryptionConfiguration:
#          NoEncryptionConfig: NoEncryption
#        ErrorOutputPrefix: !Sub 'logs/error/${ResourceName}'
#        Prefix: !Sub 'logs/info/${ResourceName}'
#      Tags: 
#        - Key: Name
#          Value: !Sub ${ResourceName}-delivery-stream
          
          
#Outputs:
#  LogGroupName:
#    Value: !Ref TestLogGroup
#    Export:
#      Name: test-loggourp-name
#  KDFARN:
#    Value: !GetAtt TestKDF.Arn
#    Export:
#      Name: test-kdf-arn