AWSTemplateFormatVersion: '2010-09-09'
Description: AWS Glue Job Stack
Resources:
  GlueJob1:
    Type: AWS::Glue::Job
    Properties:
      Name: 2175051-CFnTest-GlueJob1
      Role: arn:aws:iam::477460359712:role/2175051-testGlueRole
      Command:
        Name: pythonshell
        ScriptLocation: s3://2175051-sf-cicd-test-bucket/glue/2175051-CFnTestJob1/glue_script.py
      MaxRetries: 0
      Timeout: 5
      ExecutionProperty:
        MaxConcurrentRuns: 5
      DefaultArguments:
        '--TempDir': 's3://2175051-sf-cicd-test-bucket/glue/tmp/'
        '--PythonLibPath': 's3://2175051-sf-cicd-test-bucket/glue/lib/glue_script.py'
  GlueJob2:
    Type: AWS::Glue::Job
    Properties:
      Name: 2175051-CFnTest-GlueJob2
      Role: arn:aws:iam::477460359712:role/2175051-testGlueRole
      Command:
        Name: pythonshell
        ScriptLocation: s3://2175051-sf-cicd-test-bucket/glue/2175051-CFnTestJob2/glue_script.py
      MaxRetries: 0
      Timeout: 5
      ExecutionProperty:
        MaxConcurrentRuns: 5
      DefaultArguments:
        '--TempDir': 's3://2175051-sf-cicd-test-bucket/glue/tmp/'
        '--PythonLibPath': 's3://2175051-sf-cicd-test-bucket/glue/lib/glue_script.py'
  GlueJob3:
    Type: AWS::Glue::Job
    Properties:
      Name: 2175051-CFnTest-GlueJob3
      Role: arn:aws:iam::477460359712:role/2175051-testGlueRole
      Command:
        Name: pythonshell
        ScriptLocation: s3://2175051-sf-cicd-test-bucket/glue/2175051-CFnTestJob3/glue_script.py
      MaxRetries: 0
      Timeout: 5
      ExecutionProperty:
        MaxConcurrentRuns: 5
      DefaultArguments:
        '--TempDir': 's3://2175051-sf-cicd-test-bucket/glue/tmp/'
        '--PythonLibPath': 's3://2175051-sf-cicd-test-bucket/glue/lib/glue_script.py'
        